service: jars-serverless

frameworkVersion: "3"
custom:
  stage: "${opt:stage, self:provider.stage}"
provider:
  name: aws
  stage: "dev"
  runtime: nodejs12.x
  region: us-east-1
  environment: ${file(env.yml):${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
        - states:*
        - events:*
        - execute-api:ManageConnections
        - lambda:InvokeFunction
      Resource:
        - "*"

functions:
  create-user:
    handler: src/handler/createUser.createUser
    events:
      - http:
          path: users
          method: post
          cors: true
  get-user:
    handler: src/handler/getUser.getUser
    events:
      - http:
          path: users
          method: get
          cors: true
  update-user:
    handler: src/handler/updateUser.updateUser
    events:
      - http:
          path: users/{id}
          method: put
          cors: true
  delete-user:
    handler: src/handler/deleteUser.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
  create-movement:
    handler: src/handler/createMovement.createMovement
    events:
      - http:
          path: movements
          method: post
          cors: true
  get-movement:
    handler: src/handler/getMovement.getMovement
    events:
      - http:
          path: movements
          method: get
          cors: true
  update-movement:
    handler: src/handler/updateMovement.updateMovement
    events:
      - http:
          path: movements/{id}
          method: put
          cors: true
  delete-movement:
    handler: src/handler/deleteMovement.deleteMovement
    events:
      - http:
          path: movements/{id}
          method: delete
          cors: true
  create-jar:
    handler: src/handler/createJar.createJar
    events:
      - http:
          path: jars
          method: post
          cors: true
  get-jar:
    handler: src/handler/getJar.getJar
    events:
      - http:
          path: jars
          method: get
          cors: true
  update-jar:
    handler: src/handler/updateJar.updateJar
    events:
      - http:
          path: jars/{id}
          method: put
          cors: true
  delete-jar:
    handler: src/handler/deleteJar.deleteJar
    events:
      - http:
          path: jars/{id}
          method: delete
          cors: true
